[build]
base = "website_and_docs/"
publish = "public"
command = "hugo"

[context.production.environment]
NODE_VERSION = "18.14.1"
HUGO_VERSION = "0.110.0"
GO_VERSION = "1.20.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo"

[context.deploy-preview.environment]
NODE_VERSION = "18.14.1"
HUGO_VERSION = "0.110.0"
GO_VERSION = "1.20.1"

[context.branch-deploy]
command = "hugo --minify"

[context.branch-deploy.environment]
NODE_VERSION = "18.14.1"
HUGO_VERSION = "0.110.0"
GO_VERSION = "1.20.1"